<template>
  <div class="flex flex-row space-x-2 p-2">
    <div class="w-1/3 space-y-2">
      <p>Properties</p>
      <div v-for="(property, index) in properties" :key="index" class="p-2 border-2 border-sky-100">
        {{ property.name }}
      </div>
    </div>
    <div class="w-1/3 space-y-2">
      <p>Groups</p>
      <div v-for="(group, index) in groups" :key="index" class="flex flex-col space-y-2">
        <div class="p-2 ml-2 border-2 border-indigo-400">
          {{ group.name }}<span v-if="group.over"> partitioned by {{ group.over.name }}</span>
        </div>
        <div class="flex flex-col space-y-2">
          <div v-for="(property, index) in group.properties" :key="index" class="p-2 ml-4 border-2 border-sky-100">
            {{ property.name }}
          </div>
        </div>
      </div>
    </div>
    <div class="w-1/3">
      <p>Preview</p>
      <pre>{{ preview }}</pre>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      datas: [
        {
          property: "Hero",
          values: [
            "Mercy",
            "Moira",
            "Zenyatta",
            "Junkrat",
            "Symmetra",
            "Sojourn",
            "Orisa",
            "Doomfist",
            "Torbjörn",
            "Pharah",
            "Ana",
            "Lúcio",
            "D.Va",
            "Echo",
            "Sigma",
            "Roadhog",
            "Hanzo",
            "Soldier: 76",
            "Reaper",
            "Widowmaker",
            "Genji",
            "Zarya",
            "Ashe",
            "Bastion",
            "Reinhardt",
            "Tracer",
            "Wrecking Ball",
            "Baptiste",
            "Cassidy",
            "Brigitte",
            "Moira",
            "Mercy",
            "Sojourn",
            "Zenyatta",
            "Pharah",
            "Junkrat",
            "Orisa",
            "Torbjörn",
            "Symmetra",
            "Echo",
            "Ana",
            "Hanzo",
            "D.Va",
            "Doomfist",
            "Reaper",
            "Widowmaker",
            "Lúcio",
            "Tracer",
            "Cassidy",
            "Reinhardt",
            "Bastion",
            "Genji",
            "Roadhog",
            "Zarya",
            "Soldier: 76",
            "Brigitte",
            "Wrecking Ball",
            "Ashe",
            "Baptiste",
            "Sigma",
            "Zarya",
            "Sigma",
            "Symmetra",
            "Ana",
            "Soldier: 76",
            "Hanzo",
            "Reaper",
            "Wrecking Ball",
            "Orisa",
            "Pharah",
            "Widowmaker",
            "Ashe",
            "Mercy",
            "Zenyatta",
            "Sojourn",
            "Junkrat",
            "Tracer",
            "D.Va",
            "Cassidy",
            "Torbjörn",
            "Doomfist",
            "Lúcio",
            "Bastion",
            "Echo",
            "Genji",
            "Roadhog",
            "Baptiste",
            "Reinhardt",
            "Brigitte",
            "Moira",
            "Pharah",
            "Torbjörn",
            "Moira",
            "Echo",
            "Hanzo",
            "Sojourn",
            "Roadhog",
            "Symmetra",
            "Reaper",
            "D.Va",
            "Orisa",
            "Widowmaker",
            "Soldier: 76",
            "Junkrat",
            "Ana",
            "Doomfist",
            "Sigma",
            "Zarya",
            "Zenyatta",
            "Tracer",
            "Cassidy",
            "Wrecking Ball",
            "Lúcio",
            "Genji",
            "Bastion",
            "Mercy",
            "Reinhardt",
            "Brigitte",
            "Ashe",
            "Baptiste",
            "Mercy",
            "Torbjörn",
            "Roadhog",
            "Wrecking Ball",
            "Cassidy",
            "D.Va",
            "Genji",
            "Zenyatta",
            "Lúcio",
            "Doomfist",
            "Tracer",
            "Widowmaker",
            "Hanzo",
            "Echo",
            "Soldier: 76",
            "Reaper",
            "Bastion",
            "Reinhardt",
            "Pharah",
            "Symmetra",
            "Junkrat",
            "Zarya",
            "Ana",
            "Orisa",
            "Brigitte",
            "Moira",
            "Sojourn",
            "Ashe",
            "Baptiste",
            "Sigma",
            "Pharah",
            "Moira",
            "Reaper",
            "Tracer",
            "Mercy",
            "Hanzo",
            "Torbjörn",
            "Reinhardt",
            "Widowmaker",
            "Bastion",
            "Symmetra",
            "Zenyatta",
            "Genji",
            "Roadhog",
            "Cassidy",
            "Junkrat",
            "Zarya",
            "Soldier: 76",
            "Lúcio",
            "D.Va",
            "Doomfist",
            "Ana",
            "Orisa",
            "Brigitte",
            "Wrecking Ball",
            "Sojourn",
            "Ashe",
            "Echo",
            "Baptiste",
            "Sigma",
            "Moira",
            "Zenyatta",
            "Junkrat",
            "Sojourn",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Orisa",
            "Doomfist",
            "Ana",
            "Echo",
            "Hanzo",
            "D.Va",
            "Roadhog",
            "Soldier: 76",
            "Reaper",
            "Widowmaker",
            "Lúcio",
            "Mercy",
            "Zarya",
            "Genji",
            "Sigma",
            "Tracer",
            "Reinhardt",
            "Bastion",
            "Cassidy",
            "Brigitte",
            "Wrecking Ball",
            "Ashe",
            "Baptiste",
          ],
        },
        {
          property: "Statistic",
          values: [
            "04:18:41",
            "03:48:39",
            "02:06:07",
            "54:20",
            "46:35",
            "46:27",
            "44:09",
            "30:48",
            "28:01",
            "23:56",
            "23:47",
            "22:32",
            "15:36",
            "12:38",
            "12:09",
            "11:42",
            "11:42",
            "09:33",
            "08:12",
            "05:17",
            "05:10",
            "04:13",
            "02:42",
            "02:05",
            "01:51",
            "01:41",
            "01:25",
            "01:06",
            "01:02",
            "00:19",
            "15",
            "15",
            "4",
            "4",
            "3",
            "2",
            "2",
            "2",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "67%",
            "38%",
            "36%",
            "34%",
            "31%",
            "30%",
            "28%",
            "27%",
            "27%",
            "26%",
            "26%",
            "24%",
            "24%",
            "22%",
            "21%",
            "20%",
            "20%",
            "20%",
            "20%",
            "19%",
            "19%",
            "19%",
            "18%",
            "16%",
            "16%",
            "15%",
            "11%",
            "0",
            "0",
            "0",
            "4.22",
            "4.14",
            "3.99",
            "3.50",
            "3.00",
            "2.93",
            "2.83",
            "2.77",
            "2.67",
            "2.56",
            "2.54",
            "2.25",
            "2.00",
            "1.84",
            "1.80",
            "1.69",
            "1.40",
            "1.33",
            "1.28",
            "1.00",
            "1.00",
            "1.00",
            "0.88",
            "0.75",
            "0.50",
            "0.02",
            "0",
            "0",
            "0",
            "0",
            "17%",
            "14%",
            "13%",
            "13%",
            "13%",
            "12%",
            "11%",
            "10%",
            "10%",
            "10%",
            "9%",
            "9%",
            "9%",
            "9%",
            "8%",
            "7%",
            "1%",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "3",
            "3",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "178",
            "53",
            "32",
            "22",
            "20",
            "16",
            "16",
            "16",
            "13",
            "11",
            "11",
            "6",
            "6",
            "5",
            "5",
            "4",
            "4",
            "4",
            "3",
            "3",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
          ],
        },
        {
          property: "Category",
          values: [
            "Time Played",
            "Games Won",
            "Weapon Accuracy",
            "Eliminations per Life",
            "Critical Hit Accuracy",
            "Multikill - Best",
            "Objective Kills",
          ],
        },
        {
          property: "Username",
          values: ["ezkatka"],
        },
      ],
      transformed: [],
      properties: [],
      groups: [],
      preview: []
    };
  },

  created() {
    this.properties = this.datas.map(x => { return { name: x.property, values: x.values } })
    this.groups = [
      {
        name: "HeroStatistics",
        over: this.properties[2],
        properties: [this.properties[0], this.properties[1]]
      }
    ]

    let results = []
    for (const group of this.groups) {
      let numberOfElements = Math.max(...group.properties.map(x => x.values.length))

      let objects = []
      for (let index = 0; index < numberOfElements; index++) {
        let object = {}

        for (const groupProperty of group.properties) {
          object[groupProperty.name] = groupProperty.values[index]
        }

        objects.push(object)
      }

      if (group.over) {
        let partitions = []

        let numberOfObjects = objects.length
        let numberOfPartitions = group.over.values.length
        let numberOfElementsInPartition = numberOfObjects / numberOfPartitions

        for (let index = 0; index < numberOfPartitions; index++) {
          let from = index * numberOfElementsInPartition;
          let to = from + numberOfElementsInPartition;

          partitions.push({
            partition: group.over.values[index],
            values: objects.slice(from, to)
          })
        }

        results.push({ name: group.name, values: partitions })
        continue;
      }

      results.push({ name: group.name, values: objects })
    }
    this.preview = results;

    let groupedProperties = this.properties.reduce((acc, property) => {
      let lengthKey = property.values.length;
      let item = acc[lengthKey] ??= [];
      item.push(property)
      return acc
    }, {})
    console.log(groupedProperties);

    return;
  },
};
</script>
