<template>
  <div class="flex flex-col">
    <div class="flex flex-row p-2 space-x-2">
      <div class="w-1/2 space-y-2">
        <p>Properties</p>
        <div v-for="(property, index) in properties" :key="index" class="p-2 border-2 border-sky-100">
          {{ property.name }}
        </div>
      </div>
      <div class="w-1/2 space-y-2">
        <p>Groups</p>
        <div v-for="(group, index) in groups" :key="index" class="flex flex-col space-y-2">
          <div class="p-2 border-2 border-indigo-400">
            {{ group.name }}<span v-if="group.over"> partitioned by {{ group.over.name }}</span>
          </div>
          <div class="flex flex-col space-y-2">
            <div v-for="(property, index) in group.properties" :key="index" class="p-2 ml-4 border-2 border-sky-200">
              {{ property.alias }} from {{ property.from.name }}
            </div>
          </div>
          <div
            class="p-2 ml-4 border-2 border-teal-200"
            v-for="(mapping, index) in group.mapping"
            :key="index"
            title="Mapping field"
          >
            {{ mapping.from.name }} at index {{mapping.atIndex }}
          </div>
          <div
            class="p-2 ml-4 border-2 border-orange-200"
            v-for="(constant, index) in group.constants"
            :key="index"
            title="Constant field"
          >
            {{ constant.name }} with constant value {{ constant.value }}
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-row p-2 space-x-2">
      <div class="w-1/2">
        <p>Original</p>
        <pre>{{ properties }}</pre>
      </div>
      <div class="w-1/2">
        <p>Preview</p>
        <pre>{{ preview }}</pre>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      datas: [
        {
          property: "Username",
          values: ["ezkatka"],
        },
        {
          property: "Category",
          values: [
            "Time Played",
            "Games Won",
            "Weapon Accuracy",
            "Eliminations per Life",
            "Critical Hit Accuracy",
            "Multikill - Best",
            "Objective Kills",
          ],
        },
        {
          property: "GameMode",
          values: ["Quick Play", "Competitive Play"],
        },
        {
          property: "Platform",
          values: ["PC", "Console"],
        },
        {
          property: "QuickPlay_Hero",
          values: [
            "Mercy",
            "Moira",
            "Zenyatta",
            "Junkrat",
            "Symmetra",
            "Sojourn",
            "Orisa",
            "Doomfist",
            "Torbjörn",
            "Pharah",
            "Ana",
            "Lúcio",
            "D.Va",
            "Echo",
            "Sigma",
            "Roadhog",
            "Hanzo",
            "Soldier: 76",
            "Reaper",
            "Widowmaker",
            "Genji",
            "Zarya",
            "Ashe",
            "Bastion",
            "Reinhardt",
            "Tracer",
            "Wrecking Ball",
            "Baptiste",
            "Cassidy",
            "Brigitte",
            "Moira",
            "Mercy",
            "Zenyatta",
            "Sojourn",
            "Pharah",
            "Junkrat",
            "Orisa",
            "Torbjörn",
            "Symmetra",
            "Echo",
            "Ana",
            "Hanzo",
            "D.Va",
            "Doomfist",
            "Reaper",
            "Widowmaker",
            "Lúcio",
            "Tracer",
            "Cassidy",
            "Reinhardt",
            "Bastion",
            "Genji",
            "Roadhog",
            "Zarya",
            "Soldier: 76",
            "Brigitte",
            "Wrecking Ball",
            "Ashe",
            "Baptiste",
            "Sigma",
            "Zarya",
            "Sigma",
            "Symmetra",
            "Ana",
            "Soldier: 76",
            "Hanzo",
            "Reaper",
            "Wrecking Ball",
            "Orisa",
            "Pharah",
            "Widowmaker",
            "Ashe",
            "Mercy",
            "Zenyatta",
            "Sojourn",
            "Junkrat",
            "Tracer",
            "D.Va",
            "Cassidy",
            "Torbjörn",
            "Doomfist",
            "Lúcio",
            "Bastion",
            "Echo",
            "Genji",
            "Roadhog",
            "Baptiste",
            "Reinhardt",
            "Brigitte",
            "Moira",
            "Pharah",
            "Torbjörn",
            "Moira",
            "Echo",
            "Hanzo",
            "Sojourn",
            "Roadhog",
            "Symmetra",
            "Reaper",
            "D.Va",
            "Orisa",
            "Widowmaker",
            "Soldier: 76",
            "Junkrat",
            "Ana",
            "Doomfist",
            "Sigma",
            "Zenyatta",
            "Zarya",
            "Tracer",
            "Cassidy",
            "Wrecking Ball",
            "Lúcio",
            "Genji",
            "Bastion",
            "Mercy",
            "Reinhardt",
            "Brigitte",
            "Ashe",
            "Baptiste",
            "Mercy",
            "Torbjörn",
            "Roadhog",
            "Wrecking Ball",
            "Cassidy",
            "D.Va",
            "Genji",
            "Zenyatta",
            "Lúcio",
            "Doomfist",
            "Tracer",
            "Widowmaker",
            "Hanzo",
            "Echo",
            "Soldier: 76",
            "Reaper",
            "Bastion",
            "Reinhardt",
            "Pharah",
            "Symmetra",
            "Junkrat",
            "Zarya",
            "Ana",
            "Orisa",
            "Brigitte",
            "Moira",
            "Sojourn",
            "Ashe",
            "Baptiste",
            "Sigma",
            "Pharah",
            "Moira",
            "Reaper",
            "Tracer",
            "Mercy",
            "Hanzo",
            "Torbjörn",
            "Reinhardt",
            "Widowmaker",
            "Bastion",
            "Symmetra",
            "Zenyatta",
            "Genji",
            "Roadhog",
            "Cassidy",
            "Junkrat",
            "Zarya",
            "Soldier: 76",
            "Lúcio",
            "D.Va",
            "Doomfist",
            "Ana",
            "Orisa",
            "Brigitte",
            "Wrecking Ball",
            "Sojourn",
            "Ashe",
            "Echo",
            "Baptiste",
            "Sigma",
            "Moira",
            "Zenyatta",
            "Junkrat",
            "Sojourn",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Orisa",
            "Doomfist",
            "Ana",
            "Echo",
            "Hanzo",
            "D.Va",
            "Roadhog",
            "Soldier: 76",
            "Reaper",
            "Widowmaker",
            "Lúcio",
            "Mercy",
            "Zarya",
            "Genji",
            "Sigma",
            "Tracer",
            "Reinhardt",
            "Bastion",
            "Cassidy",
            "Brigitte",
            "Wrecking Ball",
            "Ashe",
            "Baptiste",
          ],
        },
        {
          property: "QuickPlay_Statistic",
          values: [
            "04:22:54",
            "03:48:39",
            "02:17:36",
            "54:20",
            "46:35",
            "46:27",
            "44:09",
            "30:48",
            "28:01",
            "23:56",
            "23:47",
            "22:32",
            "15:36",
            "12:38",
            "12:09",
            "11:42",
            "11:42",
            "09:33",
            "08:12",
            "05:17",
            "05:10",
            "04:13",
            "02:42",
            "02:05",
            "01:51",
            "01:41",
            "01:25",
            "01:06",
            "01:02",
            "00:19",
            "15",
            "15",
            "5",
            "4",
            "3",
            "2",
            "2",
            "2",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "67%",
            "38%",
            "36%",
            "34%",
            "31%",
            "30%",
            "28%",
            "27%",
            "27%",
            "26%",
            "26%",
            "24%",
            "24%",
            "22%",
            "21%",
            "20%",
            "20%",
            "20%",
            "20%",
            "19%",
            "19%",
            "19%",
            "18%",
            "16%",
            "16%",
            "15%",
            "11%",
            "0",
            "0",
            "0",
            "4.22",
            "4.14",
            "3.99",
            "3.50",
            "3.00",
            "2.93",
            "2.83",
            "2.77",
            "2.67",
            "2.56",
            "2.54",
            "2.25",
            "2.00",
            "1.84",
            "1.80",
            "1.69",
            "1.40",
            "1.36",
            "1.33",
            "1.00",
            "1.00",
            "1.00",
            "0.88",
            "0.75",
            "0.50",
            "0.02",
            "0",
            "0",
            "0",
            "0",
            "17%",
            "14%",
            "13%",
            "13%",
            "13%",
            "12%",
            "11%",
            "11%",
            "10%",
            "10%",
            "9%",
            "9%",
            "9%",
            "9%",
            "8%",
            "7%",
            "1%",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "3",
            "3",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "178",
            "62",
            "32",
            "22",
            "20",
            "16",
            "16",
            "16",
            "13",
            "11",
            "11",
            "6",
            "6",
            "5",
            "5",
            "4",
            "4",
            "4",
            "3",
            "3",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
          ],
        },
        {
          property: "CompetitivePlay_Hero",
          values: [
            "Orisa",
            "Zenyatta",
            "Mercy",
            "Moira",
            "Junkrat",
            "Symmetra",
            "Torbjörn",
            "Zarya",
            "Lúcio",
            "Roadhog",
            "Pharah",
            "Doomfist",
            "Ana",
            "Sigma",
            "Mercy",
            "Orisa",
            "Moira",
            "Zarya",
            "Doomfist",
            "Ana",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Roadhog",
            "Junkrat",
            "Lúcio",
            "Sigma",
            "Ana",
            "Sigma",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Torbjörn",
            "Lúcio",
            "Orisa",
            "Zarya",
            "Roadhog",
            "Junkrat",
            "Doomfist",
            "Mercy",
            "Moira",
            "Zarya",
            "Doomfist",
            "Ana",
            "Orisa",
            "Mercy",
            "Moira",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Roadhog",
            "Junkrat",
            "Lúcio",
            "Sigma",
            "Symmetra",
            "Torbjörn",
            "Zarya",
            "Moira",
            "Orisa",
            "Pharah",
            "Roadhog",
            "Junkrat",
            "Lúcio",
            "Zenyatta",
            "Mercy",
            "Doomfist",
            "Ana",
            "Sigma",
            "Doomfist",
            "Roadhog",
            "Zenyatta",
            "Torbjörn",
            "Lúcio",
            "Mercy",
            "Pharah",
            "Symmetra",
            "Junkrat",
            "Zarya",
            "Ana",
            "Orisa",
            "Moira",
            "Sigma",
            "Mercy",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Roadhog",
            "Junkrat",
            "Zarya",
            "Lúcio",
            "Doomfist",
            "Ana",
            "Orisa",
            "Moira",
            "Sigma",
            "Moira",
            "Orisa",
            "Torbjörn",
            "Junkrat",
            "Symmetra",
            "Zarya",
            "Zenyatta",
            "Roadhog",
            "Lúcio",
            "Mercy",
            "Pharah",
            "Doomfist",
            "Ana",
            "Sigma",
          ],
        },
        {
          property: "CompetitivePlay_Statistic",
          values: [
            "17:25",
            "16:07",
            "14:57",
            "14:22",
            "08:57",
            "07:44",
            "04:17",
            "03:13",
            "03:08",
            "02:06",
            "01:47",
            "01:40",
            "00:31",
            "00:21",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "67%",
            "57%",
            "46%",
            "30%",
            "26%",
            "24%",
            "23%",
            "20%",
            "18%",
            "17%",
            "17%",
            "6%",
            "0",
            "0",
            "100%",
            "100%",
            "100%",
            "37%",
            "35%",
            "25%",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "3.25",
            "3.00",
            "3.00",
            "2.44",
            "2.00",
            "1.00",
            "1.00",
            "0.67",
            "0.67",
            "0.18",
            "0",
            "0",
            "0",
            "0",
            "31%",
            "10%",
            "9%",
            "5%",
            "4%",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "13",
            "10",
            "4",
            "4",
            "2",
            "2",
            "1",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
          ],
        },
      ],
      transformed: [],
      properties: [],
      groups: [],
      preview: [],
    };
  },

  created() {
    this.properties = this.datas.map(x => {
      return { name: x.property, values: x.values };
    });
    this.groups = [
      {
        name: "PC QuickPlay HeroStatistics",
        over: this.properties[1],
        properties: [
            { from: this.properties[4], alias: "Hero"},
            { from: this.properties[5], alias: "Statistic"}
        ],
        mapping: [
          { from: this.properties[0], atIndex: 0 },
          { from: this.properties[2], atIndex: 0 },
          { from: this.properties[3], atIndex: 0 },
        ],
        constants: [
            { name: "Host", value: "https://overwatch.blizzard.com" }
        ],
      },
      {
        name: "PC CompetitivePlay HeroStatistics",
        over: this.properties[1],
        properties: [
            { from: this.properties[6], alias: "Hero"},
            { from: this.properties[7], alias: "Statistic"}
        ],
        mapping: [
          { from: this.properties[0], atIndex: 0 },
          { from: this.properties[2], atIndex: 1 },
          { from: this.properties[3], atIndex: 0 },
        ],
      },
    ];

    let results = [];
    for (const group of this.groups) {
      let numberOfElements = Math.max(...group.properties.map(x => x.from.values.length));

      let objects = [];
      for (let index = 0; index < numberOfElements; index++) {
        let object = {};

        for (const groupProperty of group.properties) {
          object[groupProperty.alias ?? groupProperty.from.name] = groupProperty.from.values[index];
        }

        objects.push(object);
      }

      if (group.over) {
        let numberOfObjects = objects.length;
        let numberOfPartitions = group.over.values.length;
        let numberOfElementsInPartition = numberOfObjects / numberOfPartitions;

        for (let index = 0; index < numberOfPartitions; index++) {
          let from = index * numberOfElementsInPartition;
          let to = from + numberOfElementsInPartition;

          for (const partitionedObject of objects.slice(from, to)) {
            partitionedObject[group.over.name] = group.over.values[index];
          }
        }
      }

      if (group.mapping) {
        for (const mapping of group.mapping) {
          for (const object of objects) {
            object[mapping.from.name] = mapping.from.values[mapping.atIndex];
          }
        }
      }

      if (group.constants) {
        for (const constant of group.constants) {
          for (const object of objects) {
            object[constant.name] = constant.value;
          }
        }
      }

      results.push({ name: group.name, values: objects });
    }

    this.preview = results.flatMap(x => x.values);

    // let groupedProperties = this.properties.reduce((acc, property) => {
    //   let lengthKey = property.values.length;
    //   let item = acc[lengthKey] ??= [];
    //   item.push(property)
    //   return acc
    // }, {})
    // console.log(groupedProperties);

    return;
  },
};
</script>
