<template>
  <div class="flex flex-col">
    <div class="flex flex-row p-2 space-x-2">
      <div class="w-1/2 space-y-2">
        <p>Properties</p>
        <div v-for="(property, index) in properties" :key="index" class="p-2 border-2 border-sky-100">
          {{ property.name }}
        </div>
      </div>
      <div class="w-1/2 space-y-2">
        <p>Groups</p>
        <div v-for="(group, index) in groups" :key="index" class="flex flex-col space-y-2">
          <div class="p-2 border-2 border-indigo-400">
            {{ group.name }}<span v-if="group.over"> partitioned by {{ group.over.name }}</span>
          </div>
          <div class="flex flex-col space-y-2">
            <div v-for="(property, index) in group.properties" :key="index" class="p-2 ml-4 border-2 border-sky-200">
              {{ property.alias }} from {{ property.from.name }}
            </div>
          </div>
          <div
            class="p-2 ml-4 border-2 border-teal-200"
            v-for="(mapping, index) in group.mapping"
            :key="index"
            title="Mapping field"
          >
            {{ mapping.from.name }} at index {{ mapping.atIndex }}
          </div>
          <div
            class="p-2 ml-4 border-2 border-orange-200"
            v-for="(constant, index) in group.constants"
            :key="index"
            title="Constant field"
          >
            {{ constant.name }} with constant value {{ constant.value }}
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-row p-2 space-x-2">
      <div class="w-1/2">
        <p>Original</p>
        <pre>{{ properties }}</pre>
      </div>
      <div class="w-1/2">
        <p>Preview</p>
        <pre>{{ preview }}</pre>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      datas: [],
      overwatch_datas: [
        {
          property: "Username",
          values: ["ezkatka"],
          "values.length": 1,
        },
        {
          property: "GameMode",
          values: ["Quick Play", "Competitive Play"],
          "values.length": 2,
        },
        {
          property: "Platform",
          values: ["PC", "Console"],
          "values.length": 2,
        },
        {
          property: "TopHero_Category",
          values: [
            "Time Played",
            "Games Won",
            "Weapon Accuracy",
            "Eliminations per Life",
            "Critical Hit Accuracy",
            "Multikill - Best",
            "Objective Kills",
          ],
          "values.length": 7,
        },
        {
          property: "TopHero_QuickPlay_Hero",
          values: [
            "MERCY",
            "MOIRA",
            "ZENYATTA",
            "JUNKRAT",
            "SYMMETRA",
            "SOJOURN",
            "Orisa",
            "Doomfist",
            "Torbjörn",
            "Pharah",
            "Ana",
            "Lúcio",
            "D.Va",
            "Echo",
            "Sigma",
            "Roadhog",
            "Hanzo",
            "Soldier: 76",
            "Reaper",
            "Widowmaker",
            "Genji",
            "Zarya",
            "Ashe",
            "Bastion",
            "Reinhardt",
            "Tracer",
            "Wrecking Ball",
            "Baptiste",
            "Cassidy",
            "Brigitte",
            "Moira",
            "Mercy",
            "Zenyatta",
            "Sojourn",
            "Pharah",
            "Junkrat",
            "Orisa",
            "Torbjörn",
            "Symmetra",
            "Echo",
            "Ana",
            "Hanzo",
            "D.Va",
            "Doomfist",
            "Reaper",
            "Widowmaker",
            "Lúcio",
            "Tracer",
            "Cassidy",
            "Reinhardt",
            "Bastion",
            "Genji",
            "Roadhog",
            "Zarya",
            "Soldier: 76",
            "Brigitte",
            "Wrecking Ball",
            "Ashe",
            "Baptiste",
            "Sigma",
            "Zarya",
            "Sigma",
            "Symmetra",
            "Ana",
            "Soldier: 76",
            "Hanzo",
            "Reaper",
            "Wrecking Ball",
            "Orisa",
            "Pharah",
            "Widowmaker",
            "Ashe",
            "Mercy",
            "Zenyatta",
            "Sojourn",
            "Junkrat",
            "Tracer",
            "D.Va",
            "Cassidy",
            "Torbjörn",
            "Doomfist",
            "Lúcio",
            "Bastion",
            "Echo",
            "Genji",
            "Roadhog",
            "Baptiste",
            "Reinhardt",
            "Brigitte",
            "Moira",
            "Pharah",
            "Torbjörn",
            "Moira",
            "Echo",
            "Hanzo",
            "Sojourn",
            "Roadhog",
            "Symmetra",
            "Reaper",
            "D.Va",
            "Orisa",
            "Widowmaker",
            "Soldier: 76",
            "Junkrat",
            "Ana",
            "Doomfist",
            "Sigma",
            "Zenyatta",
            "Zarya",
            "Tracer",
            "Cassidy",
            "Wrecking Ball",
            "Lúcio",
            "Genji",
            "Bastion",
            "Mercy",
            "Reinhardt",
            "Brigitte",
            "Ashe",
            "Baptiste",
            "Mercy",
            "Torbjörn",
            "Roadhog",
            "Wrecking Ball",
            "Cassidy",
            "D.Va",
            "Genji",
            "Zenyatta",
            "Lúcio",
            "Doomfist",
            "Tracer",
            "Widowmaker",
            "Hanzo",
            "Echo",
            "Soldier: 76",
            "Reaper",
            "Bastion",
            "Reinhardt",
            "Pharah",
            "Symmetra",
            "Junkrat",
            "Zarya",
            "Ana",
            "Orisa",
            "Brigitte",
            "Moira",
            "Sojourn",
            "Ashe",
            "Baptiste",
            "Sigma",
            "Pharah",
            "Moira",
            "Reaper",
            "Tracer",
            "Mercy",
            "Hanzo",
            "Torbjörn",
            "Reinhardt",
            "Widowmaker",
            "Bastion",
            "Symmetra",
            "Zenyatta",
            "Genji",
            "Roadhog",
            "Cassidy",
            "Junkrat",
            "Zarya",
            "Soldier: 76",
            "Lúcio",
            "D.Va",
            "Doomfist",
            "Ana",
            "Orisa",
            "Brigitte",
            "Wrecking Ball",
            "Sojourn",
            "Ashe",
            "Echo",
            "Baptiste",
            "Sigma",
            "Moira",
            "Zenyatta",
            "Junkrat",
            "Sojourn",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Orisa",
            "Doomfist",
            "Ana",
            "Echo",
            "Hanzo",
            "D.Va",
            "Roadhog",
            "Soldier: 76",
            "Reaper",
            "Widowmaker",
            "Lúcio",
            "Mercy",
            "Zarya",
            "Genji",
            "Sigma",
            "Tracer",
            "Reinhardt",
            "Bastion",
            "Cassidy",
            "Brigitte",
            "Wrecking Ball",
            "Ashe",
            "Baptiste",
          ],
          "values.length": 210,
        },
        {
          property: "TopHero_QuickPlay_Statistic",
          values: [
            "04:22:54",
            "03:48:39",
            "02:17:36",
            "54:20",
            "46:35",
            "46:27",
            "44:09",
            "30:48",
            "28:01",
            "23:56",
            "23:47",
            "22:32",
            "15:36",
            "12:38",
            "12:09",
            "11:42",
            "11:42",
            "09:33",
            "08:12",
            "05:17",
            "05:10",
            "04:13",
            "02:42",
            "02:05",
            "01:51",
            "01:41",
            "01:25",
            "01:06",
            "01:02",
            "00:19",
            "15",
            "15",
            "5",
            "4",
            "3",
            "2",
            "2",
            "2",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "67%",
            "38%",
            "36%",
            "34%",
            "31%",
            "30%",
            "28%",
            "27%",
            "27%",
            "26%",
            "26%",
            "24%",
            "24%",
            "22%",
            "21%",
            "20%",
            "20%",
            "20%",
            "20%",
            "19%",
            "19%",
            "19%",
            "18%",
            "16%",
            "16%",
            "15%",
            "11%",
            "0",
            "0",
            "0",
            "4.22",
            "4.14",
            "3.99",
            "3.50",
            "3.00",
            "2.93",
            "2.83",
            "2.77",
            "2.67",
            "2.56",
            "2.54",
            "2.25",
            "2.00",
            "1.84",
            "1.80",
            "1.69",
            "1.40",
            "1.36",
            "1.33",
            "1.00",
            "1.00",
            "1.00",
            "0.88",
            "0.75",
            "0.50",
            "0.02",
            "0",
            "0",
            "0",
            "0",
            "17%",
            "14%",
            "13%",
            "13%",
            "13%",
            "12%",
            "11%",
            "11%",
            "10%",
            "10%",
            "9%",
            "9%",
            "9%",
            "9%",
            "8%",
            "7%",
            "1%",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "3",
            "3",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "178",
            "62",
            "32",
            "22",
            "20",
            "16",
            "16",
            "16",
            "13",
            "11",
            "11",
            "6",
            "6",
            "5",
            "5",
            "4",
            "4",
            "4",
            "3",
            "3",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
          ],
          "values.length": 210,
        },
        {
          property: "TopHero_CompetitivePlay_Hero",
          values: [
            "Orisa",
            "Zenyatta",
            "Mercy",
            "Moira",
            "Junkrat",
            "Symmetra",
            "Torbjörn",
            "Zarya",
            "Lúcio",
            "Roadhog",
            "Pharah",
            "Doomfist",
            "Ana",
            "Sigma",
            "Mercy",
            "Orisa",
            "Moira",
            "Zarya",
            "Doomfist",
            "Ana",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Roadhog",
            "Junkrat",
            "Lúcio",
            "Sigma",
            "Ana",
            "Sigma",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Torbjörn",
            "Lúcio",
            "Orisa",
            "Zarya",
            "Roadhog",
            "Junkrat",
            "Doomfist",
            "Mercy",
            "Moira",
            "Zarya",
            "Doomfist",
            "Ana",
            "Orisa",
            "Mercy",
            "Moira",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Roadhog",
            "Junkrat",
            "Lúcio",
            "Sigma",
            "Symmetra",
            "Torbjörn",
            "Zarya",
            "Moira",
            "Orisa",
            "Pharah",
            "Roadhog",
            "Junkrat",
            "Lúcio",
            "Zenyatta",
            "Mercy",
            "Doomfist",
            "Ana",
            "Sigma",
            "Doomfist",
            "Roadhog",
            "Zenyatta",
            "Torbjörn",
            "Lúcio",
            "Mercy",
            "Pharah",
            "Symmetra",
            "Junkrat",
            "Zarya",
            "Ana",
            "Orisa",
            "Moira",
            "Sigma",
            "Mercy",
            "Torbjörn",
            "Pharah",
            "Symmetra",
            "Zenyatta",
            "Roadhog",
            "Junkrat",
            "Zarya",
            "Lúcio",
            "Doomfist",
            "Ana",
            "Orisa",
            "Moira",
            "Sigma",
            "Moira",
            "Orisa",
            "Torbjörn",
            "Junkrat",
            "Symmetra",
            "Zarya",
            "Zenyatta",
            "Roadhog",
            "Lúcio",
            "Mercy",
            "Pharah",
            "Doomfist",
            "Ana",
            "Sigma",
          ],
          "values.length": 112,
        },
        {
          property: "TopHero_CompetitivePlay_Value",
          values: [
            "17:25",
            "16:07",
            "14:57",
            "14:22",
            "08:57",
            "07:44",
            "04:17",
            "03:13",
            "03:08",
            "02:06",
            "01:47",
            "01:40",
            "00:31",
            "00:21",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "67%",
            "57%",
            "46%",
            "30%",
            "26%",
            "24%",
            "23%",
            "20%",
            "18%",
            "17%",
            "17%",
            "6%",
            "0",
            "0",
            "100%",
            "100%",
            "100%",
            "37%",
            "35%",
            "25%",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "3.25",
            "3.00",
            "3.00",
            "2.44",
            "2.00",
            "1.00",
            "1.00",
            "0.67",
            "0.67",
            "0.18",
            "0",
            "0",
            "0",
            "0",
            "31%",
            "10%",
            "9%",
            "5%",
            "4%",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "13",
            "10",
            "4",
            "4",
            "2",
            "2",
            "1",
            "1",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
          ],
          "values.length": 112,
        },
        {
          property: "CareerStats_Category",
          values: [
            "ALL HEROES",
            "Ana",
            "Ashe",
            "Baptiste",
            "Bastion",
            "Brigitte",
            "Cassidy",
            "D.Va",
            "Doomfist",
            "Echo",
            "Genji",
            "Hanzo",
            "Junkrat",
            "Lúcio",
            "Mercy",
            "Moira",
            "Orisa",
            "Pharah",
            "Reaper",
            "Reinhardt",
            "Roadhog",
            "Sigma",
            "Sojourn",
            "Soldier: 76",
            "Symmetra",
            "Torbjörn",
            "Tracer",
            "Widowmaker",
            "Wrecking Ball",
            "Zarya",
            "Zenyatta",
          ],
          "values.length": 31,
        },
        {
          property: "CareerStats_QuickPlay_All_Group",
          values: ["Best", "Average", "Game", "Combat", "Assists"],
          "values.length": 5,
        },
        {
          property: "CareerStats_QuickPlay_All_Title",
          values: [
            "Eliminations - Most in Game",
            "Final Blows - Most in Game",
            "All Damage Done - Most in Game",
            "Healing Done - Most in Game",
            "Defensive Assists - Most in Game",
            "Offensive Assists - Most in Game",
            "Objective Kills - Most in Game",
            "Objective Time - Most in Game",
            "Multikill - Best",
            "Solo Kills - Most in Game",
            "Time Spent on Fire - Most in Game",
            "Melee Final Blow - Most in Game",
            "Environmental Kills - Most in Game",
            "Kill Streak - Best",
            "Hero Damage Done - Most in Game",
            "Barrier Damage Done - Most in Game",
            "Assists - Most in Game",
            "Objective Contest Time - Most in Game",
            "Recon Assists - Most in Game",
            "Objective Kills - Avg per 10 Min",
            "Objective Time - Avg per 10 Min",
            "Final Blows - Avg per 10 Min",
            "Objective Contest Time - Avg per 10 Min",
            "Solo Kills - Avg per 10 Min",
            "Hero Damage Done - Avg per 10 Min",
            "Deaths - Avg per 10 Min",
            "Eliminations - Avg per 10 Min",
            "Assists - Avg per 10 min",
            "Healing Done - Avg per 10 Min",
            "Time Played",
            "Games Played",
            "Games Won",
            "Games Lost",
            "Games Won",
            "Hero Wins",
            "Games Won",
            "Environmental Kills",
            "Multikills",
            "Melee Final Blows",
            "Deaths",
            "Eliminations",
            "Objective Kills",
            "Final Blows",
            "Objective Time",
            "Hero Damage Done",
            "Objective Contest Time",
            "Solo Kills",
            "Damage Done",
            "Recon Assists",
            "Offensive Assists",
            "Defensive Assists",
            "Healing Done",
            "Assists",
          ],
          "values.length": 53,
        },
        {
          property: "CareerStats_QuickPlay_All_Values",
          values: [
            "36",
            "16",
            "17077",
            "12364",
            "24",
            "17",
            "21",
            "03:09",
            "3",
            "16",
            "05:18",
            "1",
            "2",
            "27",
            "11985",
            "4808",
            "27",
            "03:09",
            "3",
            "4.15",
            "00:42",
            "4.43",
            "00:25",
            "0.85",
            "4361",
            "6.13",
            "11.67",
            "8.86",
            "3797",
            "17:38:07",
            "123",
            "57",
            "66",
            "57",
            "57",
            "57",
            "4",
            "2",
            "5",
            "649",
            "1235",
            "439",
            "469",
            "01:14:38",
            "461482",
            "44:10",
            "90",
            "461482",
            "6",
            "308",
            "804",
            "401754",
            "937",
          ],
          "values.length": 53,
        },
        {
          property: "CareerStats_QuickPlay_Ana_Group",
          values: ["Hero Specific", "Best", "Average", "Game", "Combat", "Assists"],
          "values.length": 6,
        },
        {
          property: "CareerStats_QuickPlay_Ana_Title",
          values: [
            "Scoped Accuracy - Best in Game",
            "Self Healing",
            "Self Healing - Most in Game",
            "Enemies Slept",
            "Nano Boost Assists",
            "Unscoped Accuracy - Best in Game",
            "Enemies Slept - Most in Game",
            "Nano Boost Assists - Most in Game",
            "Biotic Grenade Kills",
            "Damage Amplified",
            "Damage Amplified - Most in Game",
            "Healing Amplified",
            "Healing Amplified - Most in Game",
            "Self Healing - Avg per 10 Min",
            "Damage Amplified - Avg per 10 Min",
            "Scoped Accuracy",
            "Biotic Grenade Kills - Avg per 10 Min",
            "Healing Amplified - Avg per 10 Min",
            "Enemies Slept - Avg per 10 Min",
            "Nano Boost Assists - Avg per 10 Min",
            "Unscoped Accuracy",
            "Eliminations - Most in Life",
            "All Damage Done - Most in Life",
            "Weapon Accuracy - Best in Game",
            "Kill Streak - Best",
            "All Damage Done - Most in Game",
            "Eliminations - Most in Game",
            "Final Blows - Most in Game",
            "Objective Kills - Most in Game",
            "Objective Time - Most in Game",
            "Solo Kills - Most in Game",
            "Hero Damage Done - Most in Game",
            "Hero Damage Done - Most in Life",
            "Assists - Most in Game",
            "Obj Contest Time - Most in Game",
            "Objective Time - Avg per 10 Min",
            "All Damage Done - Avg per 10 Min",
            "Final Blows - Avg per 10 Min",
            "Eliminations per Life",
            "Objective Kills - Avg per 10 Min",
            "Obj Contest Time - Avg per 10 Min",
            "Solo Kills - Avg per 10 Min",
            "Deaths - Avg per 10 Min",
            "Healing Done - Avg per 10 Min",
            "Hero Damage Done - Avg per 10 Min",
            "Assists - Avg per 10 min",
            "Eliminations - Avg per 10 Min",
            "Time Played",
            "Games Played",
            "Games Won",
            "Games Won",
            "Games Won",
            "Hero Wins",
            "Win Percentage",
            "Games Lost",
            "Eliminations",
            "Deaths",
            "Final Blows",
            "Solo Kills",
            "All Damage Done",
            "Objective Kills",
            "Objective Time",
            "Hero Damage Done",
            "Obj Contest Time",
            "Weapon Accuracy",
            "Offensive Assists",
            "Offensive Assists - Most in Game",
            "Defensive Assists",
            "Defensive Assists - Most in Game",
            "Healing Done",
            "Healing Done - Most in Game",
            "Assists",
            "Defensive Assists - Avg per 10 Min",
            "Offensive Assists - Avg per 10 Min",
          ],
          "values.length": 74,
        },
        {
          property: "CareerStats_QuickPlay_Ana_Values",
          values: [
            "100%",
            "211",
            "150",
            "13",
            "4",
            "57%",
            "6",
            "3",
            "4",
            "547",
            "331",
            "397",
            "231",
            "88.79",
            "230",
            "48%",
            "1.68",
            "167",
            "5.47",
            "1.68",
            "29%",
            "5",
            "2819",
            "100%",
            "5",
            "4118",
            "8",
            "2",
            "5",
            "00:29",
            "2",
            "3706",
            "2416",
            "10",
            "00:29",
            "00:24",
            "4055",
            "2.94",
            "1.80",
            "4.63",
            "00:22",
            "0.84",
            "4.21",
            "2866",
            "3732",
            "7.57",
            "7.57",
            "23:47",
            "4",
            "1",
            "1",
            "1",
            "1",
            "34%",
            "3",
            "18",
            "10",
            "7",
            "2",
            "9643",
            "11",
            "00:57",
            "8874",
            "00:52",
            "34%",
            "9",
            "6",
            "13",
            "7",
            "6814",
            "3370",
            "18",
            "5.47",
            "3.78",
          ],
          "values.length": 74,
        },
      ],
      transformed: [],
      properties: [],
      groups: [],
      preview: [],
    };
  },

  created() {
    this.properties = this.datas.map(x => {
      return { name: x.property, values: x.values };
    });

    if (this.properties.length == 0) return;

    let groupedProperties = this.properties.reduce((acc, property) => {
      let lengthKey = property.values.length;
      let item = (acc[lengthKey] ??= []);
      item.push(property);
      return acc;
    }, {});

    console.log("groupedProperties", groupedProperties);

    this.overwatch_groups = [
      {
        name: "PC QuickPlay HeroStatistics",
        over: this.properties.find(x => x.name == "TopHero_Category"),
        properties: [
          { from: this.properties.find(x => x.name == "TopHero_QuickPlay_Hero"), alias: "Hero" },
          { from: this.properties.find(x => x.name == "TopHero_QuickPlay_Statistic"), alias: "Statistic" },
        ],
        mapping: [
          { from: this.properties.find(x => x.name == "GameMode"), atIndex: 0 },
          { from: this.properties.find(x => x.name == "Platform"), atIndex: 0 },
          { from: this.properties.find(x => x.name == "Username"), atIndex: 0 },
        ],
        constants: [{ name: "Host", value: "https://overwatch.blizzard.com" }],
      },
      {
        name: "PC CompetitivePlay HeroStatistics",
        over: this.properties.find(x => x.name == "TopHero_Category"),
        properties: [
          { from: this.properties.find(x => x.name == "TopHero_CompetitivePlay_Hero"), alias: "Hero" },
          { from: this.properties.find(x => x.name == "TopHero_CompetitivePlay_Value"), alias: "Statistic" },
        ],
        mapping: [
          { from: this.properties.find(x => x.name == "GameMode"), atIndex: 0 },
          { from: this.properties.find(x => x.name == "Platform"), atIndex: 0 },
          { from: this.properties.find(x => x.name == "Username"), atIndex: 0 },
        ],
      },
      {
        name: "PC QuickPlay CareerStatistics All",
        properties: [
          { from: this.properties.find(x => x.name == "CareerStats_QuickPlay_All_Title"), alias: "Hero" },
          { from: this.properties.find(x => x.name == "CareerStats_QuickPlay_All_Values"), alias: "Statistic" },
        ],
      },
      {
        name: "PC QuickPlay CareerStatistics Ana",
        properties: [
          { from: this.properties.find(x => x.name == "CareerStats_QuickPlay_Ana_Title"), alias: "Hero" },
          { from: this.properties.find(x => x.name == "CareerStats_QuickPlay_Ana_Values"), alias: "Statistic" },
        ],
      },
    ];

    this.groups = [];

    let results = [];
    for (const group of this.groups) {
      let numberOfElements = Math.max(...group.properties.map(x => x.from.values.length));

      let objects = [];
      for (let index = 0; index < numberOfElements; index++) {
        let object = {};

        for (const groupProperty of group.properties) {
          object[groupProperty.alias ?? groupProperty.from.name] = groupProperty.from.values[index];
        }

        objects.push(object);
      }

      if (group.over) {
        let numberOfObjects = objects.length;
        let numberOfPartitions = group.over.values.length;
        let numberOfElementsInPartition = numberOfObjects / numberOfPartitions;

        for (let index = 0; index < numberOfPartitions; index++) {
          let from = index * numberOfElementsInPartition;
          let to = from + numberOfElementsInPartition;

          for (const partitionedObject of objects.slice(from, to)) {
            partitionedObject[group.over.name] = group.over.values[index];
          }
        }
      }

      if (group.mapping) {
        for (const mapping of group.mapping) {
          for (const object of objects) {
            object[mapping.from.name] = mapping.from.values[mapping.atIndex];
          }
        }
      }

      if (group.constants) {
        for (const constant of group.constants) {
          for (const object of objects) {
            object[constant.name] = constant.value;
          }
        }
      }

      results.push({ name: group.name, values: objects });
    }

    this.preview = results;
  },
};
</script>
